CREATE TABLE IF NOT EXISTS beds ( bed_id INTEGER PRIMARY KEY AUTOINCREMENT, ward_type TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'available', equipment TEXT );

CREATE TABLE IF NOT EXISTS patients ( patient_id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, age INTEGER NOT NULL, diagnosis TEXT NOT NULL );

CREATE TABLE IF NOT EXISTS admissions ( admission_id INTEGER PRIMARY KEY AUTOINCREMENT, patient_id INTEGER NOT NULL, bed_id INTEGER NOT NULL, date_in TEXT NOT NULL, date_out TEXT, FOREIGN KEY (patient_id) REFERENCES patients(patient_id), FOREIGN KEY (bed_id) REFERENCES beds(bed_id) );

CREATE TABLE IF NOT EXISTS users ( user_id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL );